name: CI (light)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable PNPM via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm -v

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Ship-it note
        run: echo "Light mode: skipping lint/typecheck/tests for now."
